language: android
jdk: oraclejdk8
before_install:
# Android SDK Platform 25
    - if [ ! -d "/usr/local/android-sdk-linux/platforms/android-25" ]; then echo y | android update sdk --no-ui --all --filter "android-25"; fi
    # Android SDK Build-tools, revision 25.0.0
    - if [ ! -d "/usr/local/android-sdk-linux/build-tools/25.0.1" ]; then echo y | android update sdk --no-ui --all --filter "build-tools-25.0.5"; fi
    # Android Support Repository, revision 39 / Local Maven repository for Support Libraries
    - if [ ! -d "/usr/local/android-sdk-linux/extras/android/m2repository/com/android/support/design/25.1.1" ]; then echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"; fi
env:
  global:
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - chmod +x gradlew
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck
